FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY config.py api.py .
RUN pip install --no-cache-dir quart sqlalchemy asyncpg
ENV QUART_APP=api:app
EXPOSE 5051
CMD ["quart", "run", "--host", "0.0.0.0", "--port", "5051"]